import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home(props) {
  const currentDate = new Date().toLocaleString();

  return (
    <div className={styles.container}>
      <Head>
        <title>Next ISR POC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js</a> ISR!
        </h1>

        <p className={styles.description}>The current time is {currentDate}</p>

        <div className={styles.description}>
          <p>This image was last updated on {props.lastUpdated}</p>
          <Image
            src={`https://picsum.photos/500/350`}
            alt="Vercel Logo"
            width={500}
            height={350}
          />
        </div>
        <div className={styles.grid}></div>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const date = new Date().toLocaleString();
  const props = { lastUpdated: date };
  return { props, revalidate: 60 };
}
