import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { getRandomPhotos } from '../utils/get-random-photo';

export default function Home(props) {
  const currentDate = new Date().toLocaleString();

  return (
    <div className={styles.container}>
      <Head>
        <title>Next ISR POC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js</a> ISR!
        </h1>

        <p className={styles.description}>The current time is {currentDate}</p>

        <div className={styles.description}>
          <p>This image was last updated on {props.lastUpdated}</p>
          <Image
            src={`https://source.unsplash.com/${props.photo.slug}`}
            alt={props.photo.description ?? props.photo.alt_description}
            width={500}
            height={350}
          />
          <p>{props.photo.description ?? props.photo.alt_description}</p>
          <p>Likes: {props.photo.likes}</p>
        </div>
        <div className={styles.grid}></div>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const date = new Date().toLocaleString();

  const photo = await getRandomPhotos();

  const props = { lastUpdated: date, photo };
  return { props, revalidate: 300 };
}
